# Generated by Django 2.2.6 on 2019-10-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_ad_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='ad_id_link',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
