# Generated by Django 2.2.6 on 2019-10-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_ad_ad_id_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='ad_image',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
